CSharp/DemoApp/MvcUI/Models/UserModel.cs
namespace MvcUI.Models
{
    public class UserModel
    {
        public int ArrayLength { get; set; }
        public string ArrayElements { get; set; }
    }
}

CSharp/DemoApp/MvcUI/Controllers/EventsController.cs
using System;
using System.Web.Mvc;
using DemoApp;
using MvcUI.Models;

namespace MvcUI.Controllers
{
    public class EventsController : Controller
    {
        public ActionResult Calculate(UserModel model)
        {
            int[] a = new int[model.ArrayLength];
            string[] strArr = model.ArrayElements.Split(' ');
            for (int i = 0; i < model.ArrayLength; i++)
            {
                a[i] = Convert.ToInt32(strArr[i]);
            }
            int sum = Logic.CalculateSum(a);
            return View(sum);
        }
    }
}

CSharp/DemoApp/MvcUI/Controllers/HomeController.cs
using System.Web.Mvc;

namespace MvcUI.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
            return View();
        }

    }
}

CSharp/DemoApp/MvcUI/Views/Events/Calculate.cshtml
@model int

<div>
    <p>Sum of the array elements is </p>
    @Model.ToString()
</div>

CSharp/DemoApp/MvcUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Hello!</h2>

@model MvcUI.Models.UserModel

@using (Html.BeginForm("Calculate", "Events"))
{
   <p>Please, print the number of elements in the array:</p>
   @Html.TextBoxFor(m => m.ArrayLength)
   <p>Please, print the elements of the array:</p>
   @Html.TextBoxFor(m => m.ArrayElements)
   <input type="submit" value="Calculate" />
}